services:
  udp_client:
    build:
      context: UDP/.
      dockerfile: Dockerfile-UDP_Client
    networks:
      - udp_network
    depends_on:
      udp_server:
        condition: service_started
    deploy:
      replicas: 5
    environment:
      - UDP_SERVER_PORT=7000
      - UDP_SERVER_NAME=udp_server

  udp_server:
    build:
      context: UDP/.
      dockerfile: Dockerfile-UDP_Server
    networks:
      - udp_network
    environment:
      - UDP_SERVER_PORT=7000
      - UDP_SERVER_NAME=udp_server
    ports:
      - "7000:7000/udp"

  tcp_server:
    build:
      context: TCP/.
      dockerfile: Dockerfile-TCP_Server
    networks:
      - tcp_network
    environment:
      - TCP_SERVER_PORT=7001
      - TCP_SERVER_NAME=tcp_server
    ports:
      - "7001:7001"

  tcp_client:
    build:
      context: TCP/.
      dockerfile: Dockerfile-TCP_Client
    networks:
      - tcp_network
    depends_on:
      tcp_server:
        condition: service_started
    deploy:
      replicas: 5
    environment:
      - TCP_SERVER_PORT=7001
      - TCP_SERVER_NAME=tcp_server

networks:
  udp_network:
    driver: bridge
  tcp_network:
    driver: bridge